### ISSUE TITLE
Documentation....

### ISSUE THREAD

**Issue by doobie42** [doobie42/OpenPegasus#1]
If you want documentation on something or help ask and I'll update/write something up.  Otherwise when I get time I'll put together some more info.

**Comment by lucaam86** [comment]
Hi, i'm not expert of firmware and electronics components but i've got a pegasus touch printer.
Can you tell me more information about your firmware update? How can I backup my actual firmware and try your firmware on my printer? 
Thanks

**Comment by tentom** [comment]
Hi, I found your code and want to test it on my printer and also contribute if i can find some time, but the "super"VAT is not so super as they(fsl) say, the liner and the acryllic is forming craks/holes and falling appart. Thus I wonder if you have some advise for a making a new liner ?

**Comment by doobie42** [comment]
Hi,

I highly recommend utilizing a secondary BBB.  I think at this point it
depends if you are familiar with Linux and BBB's.  If not; it probably
isn't for you just yet.  I'm working on building my own liner, I'll maybe
have it completed at the end of the month.

/Jason

**Comment by doobie42** [comment]
First pass at documentation on getting started with a BBB or a BBB wireless (new!) are now posted.  Please note, I have found some power supply instabilities with the BBB wireless, it may be due to an issue with my power supply, or the 24v/2.7a is just barely sufficient for the printer.

**Comment by stevj048** [comment]
Hi

Looking for help with installing firmware. Not done code before but willing to give it a go. Run command prompt  line in dos in the past but only Linux used was ubuntu. Have 2nd bbb to install on, how to create image?.
